# Generated by Django 3.1.2 on 2020-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
