# Generated by Django 3.1.2 on 2020-10-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
