# Generated by Django 3.1.2 on 2020-10-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
